departamentos = ["Ahuachapan","Sonsonate","Santa Ana","Chalatenango","Cabañas","San Salvador","La Paz","San Vicente","Usulutan","La Union","San Miguel","La Libertad","Cuscatlan","Morazan"]
municipios = [{"municipio":"1-Ahuchapan", "id_departamento":"0"},
              {"municipio":"2- Apaneca","id_departamento":"0"},
              {"municipio":"3- Atiquizaya","id_departamento":"0"},
              {"municipio":"4- Concepcion de ataco","id_departamento":"0"},
              {"municipio":"5- El Refugio","id_departamento":"0"},
              {"municipio":"6- Guaymango","id_departamento":"0"},
              {"municipio":"7- Jujutla","id_departamento":"0"},
              {"municipio":"8- San Francisco Menendez","id_departamento":"0"},
              {"municipio":"9- San Lorenzo","id_departamento":"0"},
              {"municipio":"10- San Pedro Puxtla","id_departamento":"0"},
              {"municipio":"11- Tacuba","id_departamento":"0"},
              {"municipio":"12- Turin","id_departamento":"0"},
              {"municipio":"1- Acajutla","id_departamento":"1"},
              {"municipio":"2- Armenia","id_departamento":"1"},
              {"municipio":"3- Caluco","id_departamento":"1"},
              {"municipio":"4- Cuisnahuat","id_departamento":"1"},
              {"municipio":"5- Izalco","id_departamento":"1"},
              {"municipio":"6- Juayua","id_departamento":"1"},
              {"municipio":"7- Nahuizalco","id_departamento":"1"},
              {"municipio":"8- Nahulingo","id_departamento":"1"},
              {"municipio":"9- Salcoatitan","id_departamento":"1"},
              {"municipio":"10- San Antonio del Monte","id_departamento":"1"},
              {"municipio":"11- San Julian","id_departamento":"1"},
              {"municipio":"12- Santa Catarina Masahuat","id_departamento":"1"},
              {"municipio":"13- Santa Isabel Ishuatan","id_departamento":"1"},
              {"municipio":"14- Santo Domingo de Guzman","id_departamento":"1"},
              {"municipio":"15- Sonsonate","id_departamento":"1"},
              {"municipio":"16- Sonzacate","id_departamento":"1"},
              {"municipio":"1- Candelaria de la frontera","id_departamento":"2"},
              {"municipio":"2- Chalchuapa","id_departamento":"2"},
              {"municipio":"3- Coatepeque","id_departamento":"2"},
              {"municipio":"4- El Congo","id_departamento":"2"},
              {"municipio":"5- El por venir","id_departamento":"2"},
              {"municipio":"6- Masahuat","id_departamento":"2"},
              {"municipio":"7- Metapan","id_departamento":"2"},
              {"municipio":"8- San Antonio Pajonal","id_departamento":"2"},
              {"municipio":"9- San Sebastian Salitrillo","id_departamento":"2"},
              {"municipio":"10- Santa Ana","id_departamento":"2"},
              {"municipio":"11- Santa Rosa Guachipilin","id_departamento":"2"},
              {"municipio":"12- San Tiago de la frontera","id_departamento":"2"},
              {"municipio":"13- Texistepeque","id_departamento":"2"},
              {"municipio":"1- Chalatenango","id_departamento":"3"},
              {"municipio":"2- Dulce Nombre de Maria","id_departamento":"3"},
              {"municipio":"3- San Rafael","id_departamento":"3"},
              {"municipio":"4- El Paraiso","id_departamento":"3"},
              {"municipio":"5- Agua Caliente","id_departamento":"3"},
              {"municipio":"6- Arcatao","id_departamento":"3"},
              {"municipio":"7- Azacualpa","id_departamento":"3"},
              {"municipio":"8- Cancasque","id_departamento":"3"},
              {"municipio":"9- Sitala","id_departamento":"3"},
              {"municipio":"10- Comalapa","id_departamento":"3"},
              {"municipio":"11- Concepcion Quezaltepeque","id_departamento":"3"},
              {"municipio":"12- El Carrizal","id_departamento":"3"},
              {"municipio":"13- La Laguna","id_departamento":"3"},
              {"municipio":"14- La Palma","id_departamento":"3"},
              {"municipio":"15- La Reina","id_departamento":"3"},
              {"municipio":"16- Las Flores","id_departamento":"3"},
              {"municipio":"17- Las Vueltas","id_departamento":"3"},
              {"municipio":"18- Nombre de Jesus","id_departamento":"3"},
              {"municipio":"19- Nueva Concepcion","id_departamento":"3"},
              {"municipio":"20- Nueva Trinidad","id_departamento":"3"},
              {"municipio":"21- Ojos de Agua","id_departamento":"3"},
              {"municipio":"22- Potonico","id_departamento":"3"},
              {"municipio":"23- San Antonio de la Cruz","id_departamento":"3"},
              {"municipio":"24- San Fernando","id_departamento":"3"},
              {"municipio":"25- San Francisco Lempa","id_departamento":"3"},
              {"municipio":"26- San Francisco Morazan","id_departamento":"3"},
              {"municipio":"27- San Ignacio","id_departamento":"3"},
              {"municipio":"28- San Isidro Labrador","id_departamento":"3"},
              {"municipio":"29- San Luis del Carmen","id_departamento":"3"},
              {"municipio":"30- San Miguel de Mercedez","id_departamento":"3"},
              {"municipio":"31- San Rafael","id_departamento":"3"},
              {"municipio":"32- Santa Rita","id_departamento":"3"},
              {"municipio":"33- Tejutla","id_departamento":"3"},
              {"municipio":"1- Cinquera","id_departamento":"4"},
              {"municipio":"2- Dolores","id_departamento":"4"},
              {"municipio":"3- Guacotecti","id_departamento":"4"},
              {"municipio":"4- Ilobasco","id_departamento":"4"},
              {"municipio":"5- Jutiapa","id_departamento":"4"},
              {"municipio":"6- San Isidro","id_departamento":"4"},
              {"municipio":"7- Sensuntepeque","id_departamento":"4"},
              {"municipio":"8- Tejutepque","id_departamento":"4"},
              {"municipio":"9- Victoria","id_departamento":"4"},
              {"municipio":"1- Aguilares","id_departamento":"5"},
              {"municipio":"2- Apopa","id_departamento":"5"},
              {"municipio":"3- Ayutuxtepeque","id_departamento":"5"},
              {"municipio":"4- Cuscatancingo","id_departamento":"5"},
              {"municipio":"5- Ciudad Delgado","id_departamento":"5"},
              {"municipio":"6- El Paisnal","id_departamento":"5"},
              {"municipio":"7- Guazapa","id_departamento":"5"},
              {"municipio":"8- Ilopango","id_departamento":"5"},
              {"municipio":"9- Mejicanos","id_departamento":"5"},
              {"municipio":"10- Nejapa","id_departamento":"5"},
              {"municipio":"11- Panchimalco","id_departamento":"5"},
              {"municipio":"12- Rosario de Mora","id_departamento":"5"},
              {"municipio":"13- San Marcos","id_departamento":"5"},
              {"municipio":"14- San Martin","id_departamento":"5"},
              {"municipio":"15- San Salvador","id_departamento":"5"},
              {"municipio":"16- San Tiago Texacuango","id_departamento":"5"},
              {"municipio":"17- San Tomas","id_departamento":"5"},
              {"municipio":"18- Soyapango","id_departamento":"5"},
              {"municipio":"19- Tonacatepque","id_departamento":"5"},
              {"municipio":"1- Zacatecoluca","id_departamento":"6"},
              {"municipio":"2- Olocuilta","id_departamento":"6"},
              {"municipio":"3- San Luis Talpa","id_departamento":"6"},
              {"municipio":"4- Cuyultitan","id_departamento":"6"},
              {"municipio":"5- El Rosario","id_departamento":"6"},
              {"municipio":"6- Jerusalen","id_departamento":"6"},
              {"municipio":"7- Mercedes la Ceiba","id_departamento":"6"},
              {"municipio":"8- Paraiso de Osorio","id_departamento":"6"},
              {"municipio":"9- San Antonio Masahuat","id_departamento":"6"},
              {"municipio":"10- San Emigdio","id_departamento":"6"},
              {"municipio":"11- San Francisco Chinameca","id_departamento":"6"},
              {"municipio":"12- San Pedro masahuat","id_departamento":"6"},
              {"municipio":"13- San Juan Nonualco","id_departamento":"6"},
              {"municipio":"14- San Juan Talpa","id_departamento":"6"},
              {"municipio":"15- San Juan Tepezontes","id_departamento":"6"},
              {"municipio":"16- San Luis la Herradura","id_departamento":"6"},
              {"municipio":"17- San Miguel Tepezontes","id_departamento":"6"},
              {"municipio":"18- San Pedro Nonualco","id_departamento":"6"},
              {"municipio":"19- San Rafael Obrajuelo","id_departamento":"6"},
              {"municipio":"20- Santa Maria Ostuma","id_departamento":"6"},
              {"municipio":"21- San Tiago Nonualco","id_departamento":"6"},
              {"municipio":"22- Tapalhuaca","id_departamento":"6"},
              {"municipio":"1- Apastepeque","id_departamento":"7"},
              {"municipio":"2- Guadalupe","id_departamento":"7"},
              {"municipio":"3- San Cayetano Istepeque","id_departamento":"7"},
              {"municipio":"4- San Esteban Catarina","id_departamento":"7"},
              {"municipio":"5- San Ildefonso","id_departamento":"7"},
              {"municipio":"6- San Lorenzo","id_departamento":"7"},
              {"municipio":"7- San Sebastian","id_departamento":"7"},
              {"municipio":"8- San Vicente","id_departamento":"7"},
              {"municipio":"9- Santa Clara","id_departamento":"7"},
              {"municipio":"10- Santo Domingo","id_departamento":"7"},
              {"municipio":"11- Tecoluca","id_departamento":"7"},
              {"municipio":"12- Tepetitan","id_departamento":"7"},
              {"municipio":"13- Verapaz","id_departamento":"7"},
              {"municipio":"1- Alegria","id_departamento":"8"},
              {"municipio":"2- Berlin","id_departamento":"8"},
              {"municipio":"3- California","id_departamento":"8"},
              {"municipio":"4- Concepcion Batres","id_departamento":"8"},
              {"municipio":"5- El Triunfo","id_departamento":"8"},
              {"municipio":"6- Ereguayquin","id_departamento":"8"},
              {"municipio":"7- Estanzuelas","id_departamento":"8"},
              {"municipio":"8- Jiquilisco","id_departamento":"8"},
              {"municipio":"9- Jucuapa","id_departamento":"8"},
              {"municipio":"10- Jucuaran","id_departamento":"8"},
              {"municipio":"11- Mercedes Umaña","id_departamento":"8"},
              {"municipio":"12- Nueva Granada","id_departamento":"8"},
              {"municipio":"13- Ozatlan","id_departamento":"8"},
              {"municipio":"14- Puerto el Triunfo","id_departamento":"8"},
              {"municipio":"15- San Agustin","id_departamento":"8"},
              {"municipio":"16- San Buenaventura","id_departamento":"8"},
              {"municipio":"17- San Dionisio","id_departamento":"8"},
              {"municipio":"18- San Francisco Javier","id_departamento":"8"},
              {"municipio":"19- Santa Elena","id_departamento":"8"},
              {"municipio":"20- Santa Maria","id_departamento":"8"},
              {"municipio":"21- Santiago de Maria","id_departamento":"8"},
              {"municipio":"22- Tecapan","id_departamento":"8"},
              {"municipio":"23- Usulutan","id_departamento":"8"},
              {"municipio":"1- Anamoros","id_departamento":"9"},
              {"municipio":"2- Bolivar","id_departamento":"9"},
              {"municipio":"3- Concepcion de Oriente","id_departamento":"9"},
              {"municipio":"4- Conchagua","id_departamento":"9"},
              {"municipio":"5- El Carmen","id_departamento":"9"},
              {"municipio":"6- El sauce","id_departamento":"9"},
              {"municipio":"7- Intipuca","id_departamento":"9"},
              {"municipio":"8- La Union","id_departamento":"9"},
              {"municipio":"9- Lislique","id_departamento":"9"},
              {"municipio":"10- Meanguera del Golfo","id_departamento":"9"},
              {"municipio":"11- Nueva Esparta","id_departamento":"9"},
              {"municipio":"12- Pasaquina","id_departamento":"9"},
              {"municipio":"13- Poloros","id_departamento":"9"},
              {"municipio":"14- San Alejo","id_departamento":"9"},
              {"municipio":"15- San Jose","id_departamento":"9"},
              {"municipio":"16- Santa Rosa de Lima","id_departamento":"9"},
              {"municipio":"17- Yayantique","id_departamento":"9"},
              {"municipio":"18- Yucuaquin","id_departamento":"9"},
              {"municipio":"1- Carolina","id_departamento":"10"},
              {"municipio":"2- Chapeltique","id_departamento":"10"},
              {"municipio":"3- Chinameca","id_departamento":"10"},
              {"municipio":"4- Chirilagua","id_departamento":"10"},
              {"municipio":"5- Ciudad Barrios","id_departamento":"10"},
              {"municipio":"6- Comacaran","id_departamento":"10"},
              {"municipio":"7- El Transito","id_departamento":"10"},
              {"municipio":"8- Lolotique","id_departamento":"10"},
              {"municipio":"9- Moncagua","id_departamento":"10"},
              {"municipio":"10- Nueva Guadalupe","id_departamento":"10"},
              {"municipio":"11- Nuevo Eden de San Juan","id_departamento":"10"},
              {"municipio":"12- Quelepa","id_departamento":"10"},
              {"municipio":"13- San Antonio del Mosco","id_departamento":"10"},
              {"municipio":"14- San Gerardo","id_departamento":"10"},
              {"municipio":"15- San Jorge","id_departamento":"10"},
              {"municipio":"16- San Luis de la Reina","id_departamento":"10"},
              {"municipio":"17- San Miguel","id_departamento":"10"},
              {"municipio":"18- San Rafael Oriente","id_departamento":"10"},
              {"municipio":"19- Sesori","id_departamento":"10"},
              {"municipio":"20- Uluazapa","id_departamento":"10"},
              {"municipio":"1- Antiguo Cuscatlan","id_departamento":"11"},
              {"municipio":"2- Chiltiupan","id_departamento":"11"},
              {"municipio":"3- Ciudad Arce","id_departamento":"11"},
              {"municipio":"4- Colon","id_departamento":"11"},
              {"municipio":"5- Comasagua","id_departamento":"11"},
              {"municipio":"6- Huizucar","id_departamento":"11"},
              {"municipio":"7- Jayaque","id_departamento":"11"},
              {"municipio":"8- Jicalapa","id_departamento":"11"},
              {"municipio":"9- La Libertad","id_departamento":"11"},
              {"municipio":"10- Santa Tecla","id_departamento":"11"},
              {"municipio":"11- Nuevo Cuscatlan","id_departamento":"11"},
              {"municipio":"12- San Juan Opico","id_departamento":"11"},
              {"municipio":"13- Quezaltepeque","id_departamento":"11"},
              {"municipio":"14- Sacacoyo","id_departamento":"11"},
              {"municipio":"15- San Jose Villa Nueva","id_departamento":"11"},
              {"municipio":"16- San Matias","id_departamento":"11"},
              {"municipio":"17- San Pablo Tacachico","id_departamento":"11"},
              {"municipio":"18- Talnique","id_departamento":"11"},
              {"municipio":"19- Tamanique","id_departamento":"11"},
              {"municipio":"20- Teotepeque","id_departamento":"11"},
              {"municipio":"21- Tepecoyo","id_departamento":"11"},
              {"municipio":"22- Zaragoza","id_departamento":"11"},
              {"municipio":"1- Candelaria","id_departamento":"12"},
              {"municipio":"2- Cojutepeque","id_departamento":"12"},
              {"municipio":"3- El Carmen","id_departamento":"12"},
              {"municipio":"4- El Rosario","id_departamento":"12"},
              {"municipio":"5- Monte San Juan","id_departamento":"12"},
              {"municipio":"6- Oratorio de Concepcion","id_departamento":"12"},
              {"municipio":"7- San Bartolome Perulapia","id_departamento":"12"},
              {"municipio":"8- San Cristobal","id_departamento":"12"},
              {"municipio":"9- San Jose Guayabal","id_departamento":"12"},
              {"municipio":"10- San Pedro perulapan","id_departamento":"12"},
              {"municipio":"11- San Rafael Cedros","id_departamento":"12"},
              {"municipio":"12- San Ramon","id_departamento":"12"},
              {"municipio":"13- Santa Cruz Analquito","id_departamento":"12"},
              {"municipio":"14- Santa Cruz Michapa","id_departamento":"12"},
              {"municipio":"15- Suchitoto","id_departamento":"12"},
              {"municipio":"16- Tenalcingo","id_departamento":"12"},
              {"municipio":"1- Arambala","id_departamento":"13"},
              {"municipio":"2- Cacaopera","id_departamento":"13"},
              {"municipio":"3- Chilanga","id_departamento":"13"},
              {"municipio":"4- Corinto","id_departamento":"13"},
              {"municipio":"5- Delicias de Concepcion","id_departamento":"13"},
              {"municipio":"6- El Divisadero","id_departamento":"13"},
              {"municipio":"7- El Rosario","id_departamento":"13"},
              {"municipio":"8- Gualacocti","id_departamento":"13"},
              {"municipio":"9- Guatajiagua","id_departamento":"13"},
              {"municipio":"10- Joateca","id_departamento":"13"},
              {"municipio":"11- Jocoaitique","id_departamento":"13"},
              {"municipio":"12- Jocoro","id_departamento":"13"},
              {"municipio":"13- Lolotiquillo","id_departamento":"13"},
              {"municipio":"14- Meanguera","id_departamento":"13"},
              {"municipio":"15- Osicala","id_departamento":"13"},
              {"municipio":"16- Perquin","id_departamento":"13"},
              {"municipio":"17- San Carlos","id_departamento":"13"},
              {"municipio":"18- San Fernando","id_departamento":"13"},
              {"municipio":"19- San Francisco Gotera","id_departamento":"13"},
              {"municipio":"20- San Isidro","id_departamento":"13"},
              {"municipio":"21- San Simon","id_departamento":"13"},
              {"municipio":"22- Sensembra","id_departamento":"13"},
              {"municipio":"23- Sociedad","id_departamento":"13"},
              {"municipio":"24- Torola","id_departamento":"13"},
              {"municipio":"25- Yamabal","id_departamento":"13"},
              {"municipio":"26- Yoloaiquin","id_departamento":"13"},]
            
def StarProgram():
    
    respuesta = input("Quiere Ingresar al programa (SI/NO): ").upper()
    if respuesta == "SI":
        i = 1
        #Imprimir lista de los departamentos
        for depar in departamentos:
            print(f"{i}- {depar}")
            i += 1
        #Bucle para buscar el departamento
        seguir = True
        while seguir == True:
            depart_buscar = input("Ingresa el 'Nombre' del departamento que quiera saber sus municipios: ")
            print(f"Estos son los municipios de: {depart_buscar}")
            if depart_buscar in departamentos:
                j = departamentos.index(depart_buscar)
                #print(f"si se encuentra en la posicio: {j}")
                for i in range(len(municipios)):
                    if str(j) == municipios[i]['id_departamento']:
                        print(f"{municipios[i]['municipio']}")
                question = input("Quiere consultar otro departamento:\n1-SI\n2-NO\n=>  ").upper()
                if question == "NO" or question == "2":
                    break
            else:
                print("Este municipio no se encuentra")
                
    else:
        print("Programa no ejecutado.")
        print("Finalizando Programa...")
StarProgram()
print("Programa Finalizado con exito")